export const REQUEST_GET_SERVERS_LIST = 'REQUEST_GET_SERVERS_LIST';

export const APPLY_SERVERS_OVERVIEW_FILTERS_RULES = 'APPLY_SERVERS_OVERVIEW_FILTERS_RULES';
export const SORTING_SERVERS_BY_PARAMETR = 'SORTING_SERVERS_BY_PARAMETR';
export const SET_CURRENT_URL_WITH_QUERY_PARAMETR = 'SET_CURRENT_URL_WITH_QUERY_PARAMETR';
export const CHECK_URL_FOR_UPDATING_FILTERS = 'CHECK_URL_FOR_UPDATING_FILTERS';
export const serversEndpoints = {
	[REQUEST_GET_SERVERS_LIST]: '.netlify/functions/servers',
};

